name: Publish to GitHub Packages

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create .npmrc file
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_PAT }}" >> .npmrc
          echo "@vetching-corporation:registry=https://npm.pkg.github.com/" >> .npmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
          scope: '@vetching-corporation'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build dependencies
        run: pnpm build

      - name: Update package name & version
        run: |
          # 깃 태그에서 추출한 버전 값
          echo "Target version: $VERSION"

          # 버전 업데이트
          jq --arg version "$VERSION" '.version = $version' package.json > tmp && mv tmp package.json

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Prisma cli 패키지 배포
          pnpm publish --no-git-checks
